import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import SunCalc from '../vendor/suncalc.mjs';

test('vendored SunCalc exposes the methods we depend on', () => {
  assert.equal(typeof SunCalc.getMoonPosition, 'function');
  assert.equal(typeof SunCalc.getMoonIllumination, 'function');
  assert.equal(typeof SunCalc.getMoonTimes, 'function');
  assert.equal(typeof SunCalc.getTimes, 'function');
});

test('SunCalc computes a plausible moon altitude for Durban', () => {
  const pos = SunCalc.getMoonPosition(new Date('2026-08-19T12:00:00Z'), -29.85, 31.05);
  assert.equal(typeof pos.altitude, 'number');
  assert.ok(pos.altitude >= -Math.PI / 2 && pos.altitude <= Math.PI / 2);
});

test('every js module is precached by the service worker', async () => {
  const sw = readFileSync(new URL('../sw.js', import.meta.url), 'utf8');
  const modules = (await readdir(new URL('../js/', import.meta.url)))
    .filter((f) => f.endsWith('.js'));

  // main.js imports these eagerly, so a module missing from SHELL breaks the
  // whole app offline -- not just its own feature.
  const missing = modules.filter((f) => !sw.includes(`'./js/${f}'`));

  assert.deepEqual(missing, [], `not precached: ${missing.join(', ')}`);
});

test('the feed JSON files are deliberately NOT precached', () => {
  const sw = readFileSync(new URL('../sw.js', import.meta.url), 'utf8');

  // caches.addAll is atomic: a listed-but-absent file fails the whole install.
  // These are generated by a cron and may not exist yet.
  assert.equal(sw.includes('data/feeds/'), false, 'feed JSON must stay out of SHELL');
});
